version: 2
jobs:
  build:
    docker:
      - image: docker:18.03.0-ce
    working_directory: /home/socks5-server/
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            apk update && apk add curl
            VER="18.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Build Docker image
          command:
            docker build -t f355/go-socks5-proxy .
      - deploy:
          command: |
            docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
            if [ $CIRCLE_TAG -ne "undefined" ];
            then
              docker tag f355/go-socks5-proxy f355/go-socks5-proxy:$CIRCLE_TAG
              docker push f355/go-socks5-proxy:$CIRCLE_TAG
            else
              docker tag f355/go-socks5-proxy f355/go-socks5-proxy:dev
              docker push f355/go-socks5-proxy:dev
            fi
